name: wwc2207
location: eastus
apiVersion: '2021-07-01'
properties:
  containers:
  - name: streamlitapp
    properties:
      image: wwc2207.azurecr.io/calihouse_ml_app:v1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
  imageRegistryCredentials:
  - server: wwc2207.azurecr.io
    username: wwc2207
    password: glKMIxRt+DLz8SFEp5UAwyHHCPPaKbEX
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: calihouseprice
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups